name: genesis
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
# Note: For CUDA support, install PyTorch manually:
# pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
- pytorch
- torchvision
- torchaudio
- pytorch-cuda=11.8
  - numpy
  - scipy
  - matplotlib
  - h5py
  - pyyaml
  - tqdm
  - psutil
  - pip
  - pip:
    - tensorboard
    - wandb
 