name: genesis
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - scipy
  - matplotlib
  - h5py
  - pyyaml
  - tqdm
  - pip
  - pip:
    - tensorboard
    - wandb
