# Quadratic Noise Schedule Configuration for GENESIS

experiment_name: "icecube_diffusion_quadratic"
description: "DiT architecture with quadratic noise schedule"

# Model configuration
model:
  architecture: "dit"
  seq_len: 5160
  hidden: 512
  depth: 8
  heads: 8
  dropout: 0.1
  fusion: "FiLM"
  label_dim: 6
  t_embed_dim: 128
  mlp_ratio: 4.0
  kernel_size: 3
  kernel_sizes: [3, 5, 7, 9]
  
  # Signal + Geometry affine normalization: [charge, time, x, y, z]
  # Formula: (x - offset) / scale → charge/time[-2,2], pos[-1,1]
  affine_offsets: [0.0, 0.0, 0.0, 0.0, 0.0]  # Offset values
  affine_scales: [100.0, 10.0, 600.0, 550.0, 550.0]  # Scale factors
  
  # Label affine normalization: [Energy, Zenith, Azimuth, X, Y, Z]
  label_offsets: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  label_scales: [50000000.0, 1.0, 1.0, 600.0, 550.0, 550.0]  # Normalize Energy and positions
  
  # Time transformation
  time_transform: "ln"  # "log10", "ln", or null
  exclude_zero_time: true  # Exclude zero time values (recommended for log transforms)

# Diffusion configuration with Quadratic Schedule
diffusion:
  timesteps: 1000
  beta_start: 0.0001  # Starting noise level
  beta_end: 0.02      # Ending noise level
  objective: "eps"    # Predict noise (ε-prediction)
  schedule: "quadratic"  # Quadratic beta schedule
  
  # Classifier-free guidance
  use_cfg: true
  cfg_scale: 2.0      # Guidance strength (higher = more conditioning)
  cfg_dropout: 0.1    # Dropout rate for unconditional training

# Data configuration
data:
  # Git repository 루트 기준으로 데이터 경로 설정
  h5_path: "${GENESIS_ROOT}GENESIS-data/22644_0921_time_shift.h5"
  replace_time_inf_with: 0.0
  channel_first: true
  batch_size: 32      # Moderate batch size for quadratic schedule
  num_workers: 8
  pin_memory: true
  shuffle: true
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1

# Training configuration optimized for quadratic schedule
training:
  num_epochs: 280     # Moderate epochs for quadratic schedule
  learning_rate: 0.00015  # Moderate learning rate
  weight_decay: 0.01
  grad_clip_norm: 1.0
  optimizer: "AdamW"
  scheduler: "cosine"  # Use cosine for training scheduler
  warmup_steps: 1800
  
  # Early stopping
  early_stopping: true
  early_stopping_patience: 28
  early_stopping_min_delta: 1e-4
  early_stopping_mode: "min"
  early_stopping_baseline: null
  early_stopping_restore_best: true
  early_stopping_verbose: true
  
  # Logging and checkpointing
  log_interval: 50
  save_interval: 1000
  eval_interval: 500
  output_dir: "./outputs/quadratic"
  checkpoint_dir: "./checkpoints/quadratic"
  log_dir: "./logs/quadratic"
  resume_from_checkpoint: null
  use_amp: true
  debug_mode: false
  detect_anomaly: false

# System settings
device: "auto"
seed: 42

# Logging
use_wandb: false
wandb_project: "icecube-diffusion-quadratic"
wandb_entity: null
