# Configuration for C-Dit (Classifier-Attention DiT) Model

experiment_name: "icecube_c_dit"
description: "Classifier-Attention based Diffusion Transformer with cross-attention mechanism"

# Model configuration - C-Dit
model:
  architecture: "c-dit"
  seq_len: 5160
  hidden: 16                    # PMT token hidden dimension
  classifier_size: 128          # Classifier (latent) token dimension
  depth: 2                      # Number of transformer blocks
  heads: 2                      # Number of attention heads
  dropout: 0.1
  factor: 2                     # MLP expansion factor
  label_dim: 6
  t_embed_dim: 128
  
  # C-Dit specific parameters
  combine: "add"                # How to combine signal and geometry ("add" or "concat")
  update_with_classifier: false # If true, PMT tokens are updated with classifier info
  n_cls_tokens: 1               # Number of classifier (latent) tokens
  
  # Normalization metadata (for denormalization during sampling)
  # Formula: (x - offset) / scale → [0, 1]
  affine_offsets: [0.0, 0.0, -600.0, -550.0, -550.0]  # [charge, time, x, y, z]
  affine_scales: [200.0, 10.0, 1200.0, 1100.0, 1100.0]
  label_offsets: [0.0, 0.0, 0.0, -600.0, -550.0, -550.0]  # [Energy, Zenith, Azimuth, X, Y, Z]
  label_scales: [100000000.0, 3.14159, 6.28318, 1200.0, 1100.0, 1100.0]
  time_transform: "ln"

# Diffusion configuration
diffusion:
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  schedule: "linear"
  objective: "eps"
  
  # Classifier-free guidance
  use_cfg: true
  cfg_scale: 2.0
  cfg_dropout: 0.1

# Data configuration
data:
  h5_path: "~/GENESIS/GENESIS-data/22644_0921_time_shift.h5"
  replace_time_inf_with: 0.0
  channel_first: true
  batch_size: 512
  num_workers: 40
  pin_memory: true
  shuffle: true
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  
  # Normalization (applied in Dataloader) - Normalize to [0, 1]
  time_transform: "ln"  # "ln" or "log10" - applied BEFORE affine
  affine_offsets: [0.0, 0.0, -600.0, -550.0, -550.0]  # [charge, time_ln, x, y, z]
  affine_scales: [200.0, 10.0, 1200.0, 1100.0, 1100.0]
  label_offsets: [0.0, 0.0, 0.0, -600.0, -550.0, -550.0]  # [Energy, Zenith, Azimuth, X, Y, Z]
  label_scales: [100000000.0, 3.14159, 6.28318, 1200.0, 1100.0, 1100.0]

# Training configuration
training:
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.01
  grad_clip_norm: 1.0
  optimizer: "AdamW"
  scheduler: "plateau"
  warmup_steps: 1000
  warmup_ratio: 0.04  # 4% warmup
  
  # Plateau scheduler
  plateau_patience: 2
  plateau_factor: 0.7
  plateau_mode: "min"
  plateau_threshold: 1e-4
  plateau_cooldown: 0
  
  # Early stopping
  early_stopping: true
  early_stopping_patience: 5
  early_stopping_min_delta: 1e-4
  early_stopping_mode: "min"
  early_stopping_baseline: null
  early_stopping_restore_best: true
  early_stopping_verbose: true
  
  log_interval: 50
  save_interval: 1000
  eval_interval: 1
  output_dir: "outputs"
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  resume_from_checkpoint: null
  use_amp: true
  debug_mode: false
  detect_anomaly: false

# System settings
device: "auto"
seed: 42

# Logging
use_wandb: false
wandb_project: "icecube-diffusion"
wandb_entity: null

