# Hybrid CNN-Transformer architecture configuration for GENESIS

experiment_name: "icecube_diffusion_hybrid"
description: "Hybrid CNN-Transformer architecture for IceCube muon neutrino event diffusion model"

# Model configuration
model:
  architecture: "hybrid"
  seq_len: 5160
  hidden: 384
  depth: 6
  heads: 6
  dropout: 0.1
  fusion: "FiLM"  # Not used in hybrid but kept for compatibility
  label_dim: 6
  t_embed_dim: 128
  mlp_ratio: 4.0
  kernel_size: 3
  kernel_sizes: [3, 5, 7, 9]  # Not used in hybrid but kept for compatibility
  
  # Signal + Geometry affine normalization: [charge, time, x, y, z]
  # Formula: (x - offset) / scale → charge/time[-2,2], pos[-1,1]
  affine_offsets: [0.0, 0.0, 0.0, 0.0, 0.0]  # Offset values
  affine_scales: [100.0, 10.0, 600.0, 550.0, 550.0]  # Scale factors
  
  # Label affine normalization: [Energy, Zenith, Azimuth, X, Y, Z]
  label_offsets: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  label_scales: [50000000.0, 1.0, 1.0, 600.0, 550.0, 550.0]  # Normalize Energy and positions
  
  # Time transformation
  time_transform: "ln"  # "log10", "ln", or null
  exclude_zero_time: true  # Exclude zero time values (recommended for log transforms)

# Diffusion configuration
diffusion:
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  objective: "eps"
  schedule: "linear"
  
  # Classifier-free guidance
  use_cfg: true
  cfg_scale: 2.0
  cfg_dropout: 0.1

# Data configuration
data:
  h5_path: "/home/work/GENESIS/GENESIS-data/22644_0921.h5"
  replace_time_inf_with: 0.0
  channel_first: true
  batch_size: 12  # Moderate batch size for hybrid
  num_workers: 4
  pin_memory: true
  shuffle: true
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1

# Training configuration
training:
  num_epochs: 50
  learning_rate: 0.0002
  weight_decay: 0.01
  grad_clip_norm: 1.0
  optimizer: "AdamW"
  scheduler: null
  warmup_steps: 1000
  
  # Early stopping
  early_stopping: false
  early_stopping_patience: 15
  early_stopping_min_delta: 1e-4
  early_stopping_mode: "min"
  early_stopping_baseline: null
  early_stopping_restore_best: true
  early_stopping_verbose: true
  
  log_interval: 50
  save_interval: 1000
  eval_interval: 500
  output_dir: "./outputs"
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"
  resume_from_checkpoint: null
  use_amp: true
  debug_mode: false
  detect_anomaly: false

# System settings
device: "auto"
seed: 42

# Logging
use_wandb: false
wandb_project: "icecube-diffusion"
wandb_entity: null
