# Cosine Annealing configuration for GENESIS IceCube diffusion model

experiment_name: "icecube_diffusion_cosine"
description: "Configuration with Cosine Annealing scheduler for periodic LR cycling"

# Model configuration
model:
  seq_len: 5160
  hidden: 16 #512
  depth: 3
  heads: 8
  dropout: 0.1
  fusion: "SUM"  # Changed to SUM for stability
  label_dim: 6
  t_embed_dim: 128
  mlp_ratio: 4.0
  # Signal + Geometry affine normalization: [charge, time, x, y, z]
  # Formula: (x - offset) / scale → charge/time to reasonable range, pos[-1,1]
  affine_offsets: [0.0, 0.0, 0.0, 0.0, 0.0]  # Offset values
  affine_scales: [100.0, 10.0, 600.0, 550.0, 550.0]  # Scale factors
  # Label affine normalization: [Energy, Zenith, Azimuth, X, Y, Z]
  label_offsets: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  label_scales: [50000000.0, 1.0, 1.0, 600.0, 550.0, 550.0]  # Normalize Energy and positions
  
  # Time transformation: Always use log(1+x) - handles zeros naturally
  # - Formula: ln(1 + time) or log10(1 + time)
  # - log(1 + 0) = 0 (zeros handled naturally, no special case needed)
  # - Inverse: exp(y) - 1 or 10^y - 1
  time_transform: "ln"  # "log10" or "ln"

# Diffusion configuration
diffusion:
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  objective: "eps"  # "eps" or "x0"
  schedule: "linear"  # "linear" or "cosine"
  
  # Classifier-free guidance
  use_cfg: true
  cfg_scale: 2.0
  cfg_dropout: 0.1

# Data configuration
data:
  h5_path: "GENESIS-data/22644_0921.h5"
  replace_time_inf_with: 0.0
  channel_first: true
  batch_size: 512
  num_workers: 40
  pin_memory: true
  shuffle: true
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1

# Training configuration with Cosine Annealing
training:
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.01
  grad_clip_norm: 1.0
  optimizer: "AdamW"
  scheduler: "cosine"
  warmup_steps: 1000
  warmup_ratio: 0.04
  
  # Cosine scheduler parameters
  cosine_t_max: 2
  
  # Early stopping
  early_stopping: true
  early_stopping_patience: 5
  early_stopping_min_delta: 1e-4
  early_stopping_mode: "min"
  early_stopping_baseline: null
  early_stopping_restore_best: true
  early_stopping_verbose: true
  
  log_interval: 50
  save_interval: 1000  # Not used (epoch-based saving)
  eval_interval: 1
  output_dir: "outputs"
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  resume_from_checkpoint: null
  use_amp: true
  debug_mode: false
  detect_anomaly: false

# System settings
device: "auto"
seed: 42

# Logging
use_wandb: false
wandb_project: "icecube-diffusion"
wandb_entity: null

