# Debug configuration for development and testing

experiment_name: "icecube_diffusion_debug"
description: "Debug configuration for development and testing"

# Model configuration - minimal architecture
model:
  seq_len: 5160
  hidden: 128
  depth: 2
  heads: 2
  dropout: 0.1
  fusion: "SUM"  # Changed to SUM for simplicity, "FiLM" is the default
  label_dim: 6
  t_embed_dim: 32
  mlp_ratio: 4.0
  
  # Signal + Geometry affine normalization: [charge, time, x, y, z]
  # Formula: (x - offset) / scale → charge/time[-2,2], pos[-1,1]
  affine_offsets: [112.5, 67616.0, 0.0, 0.0, 0.0]  # Offset values
  affine_scales: [56.25, 33808.0, 500.0, 500.0, 500.0]  # Scale factors
  
  # Label affine normalization: [Energy, Zenith, Azimuth, X, Y, Z]
  label_offsets: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  label_scales: [1e-7, 1.0, 1.0, 0.01, 0.01, 0.01]  # Normalize Energy and positions
  
  # Time transformation
  time_transform: "ln"  # "log10", "ln", or null
  exclude_zero_time: true  # Exclude zero time values (recommended for log transforms)

# Diffusion configuration - very few timesteps
diffusion:
  timesteps: 10
  beta_start: 0.0001
  beta_end: 0.02
  objective: "eps"

# Data configuration
data:
  h5_path: "/home/work/GENESIS/GENESIS-data/22644_0921.h5"
  replace_time_inf_with: 0.0
  channel_first: true
  batch_size: 2
  num_workers: 0
  pin_memory: false
  shuffle: true
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1

# Training configuration - very short training
training:
  num_epochs: 2
  learning_rate: 0.0002
  weight_decay: 0.01
  grad_clip_norm: 1.0
  optimizer: "AdamW"
  scheduler: null
  warmup_steps: 10
  
  # Early stopping (disabled for debug)
  early_stopping: false
  early_stopping_patience: 5
  early_stopping_min_delta: 1e-3
  early_stopping_mode: "min"
  early_stopping_baseline: null
  early_stopping_restore_best: true
  early_stopping_verbose: true
  
  log_interval: 1
  save_interval: 10
  eval_interval: 5
  output_dir: "./outputs"
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"
  resume_from_checkpoint: null
  use_amp: false
  debug_mode: true
  detect_anomaly: true

# System settings
device: "auto"
seed: 42

# Logging
use_wandb: false
wandb_project: "icecube-diffusion"
wandb_entity: null
