experiment_name: dit_linear_plateau
description: DIT model with linear noise schedule and plateau LR scheduler
model:
  architecture: dit
  seq_len: 5160
  hidden: 256
  depth: 4
  heads: 8
  dropout: 0.1
  fusion: FiLM
  label_dim: 6
  t_embed_dim: 128
  mlp_ratio: 4.0
  affine_offsets:
  - 0.0
  - 0.0
  - -600.0
  - -550.0
  - -550.0
  affine_scales:
  - 200.0
  - 10.0
  - 1200.0
  - 1100.0
  - 1100.0
  label_offsets:
  - 0.0
  - 0.0
  - 0.0
  - -600.0
  - -550.0
  - -550.0
  label_scales:
  - 100000000.0
  - 3.14159
  - 6.28318
  - 1200.0
  - 1100.0
  - 1100.0
  time_transform: ln
diffusion:
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  objective: eps
  schedule: linear
  use_cfg: true
  cfg_scale: 2.0
  cfg_dropout: 0.1
data:
  h5_path: /home/work/GENESIS/GENESIS-pmj0324/GENESIS/GENESIS-data/22644_0921_time_shift.h5
  replace_time_inf_with: 0.0
  channel_first: true
  batch_size: 512
  num_workers: 40
  pin_memory: true
  shuffle: true
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  time_transform: ln
  affine_offsets:
  - 0.674553394317627
  - 0.3472016751766205
  - -600.0
  - -550.0
  - -550.0
  affine_scales:
  - 6.265065670013428
  - 1.5873996019363403
  - 1200.0
  - 1100.0
  - 1100.0
  label_offsets:
  - 0.0
  - 0.0
  - 0.0
  - -600.0
  - -550.0
  - -550.0
  label_scales:
  - 100000000.0
  - 3.14159
  - 6.28318
  - 1200.0
  - 1100.0
  - 1100.0
training:
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.01
  grad_clip_norm: 1.0
  optimizer: AdamW
  scheduler: plateau
  warmup_steps: 1000
  warmup_ratio: 0.04
  plateau_patience: 2
  plateau_factor: 0.5
  plateau_mode: min
  plateau_threshold: 1e-6
  plateau_cooldown: 0
  early_stopping: true
  early_stopping_patience: 5
  early_stopping_min_delta: 1e-4
  early_stopping_mode: min
  early_stopping_baseline: null
  early_stopping_restore_best: true
  early_stopping_verbose: true
  log_interval: 50
  save_interval: 1000
  eval_interval: 1
  output_dir: outputs
  checkpoint_dir: checkpoints
  log_dir: logs
  resume_from_checkpoint: null
  use_amp: true
  debug_mode: false
  detect_anomaly: false
device: auto
seed: 42
use_wandb: false
wandb_project: icecube-diffusion
wandb_entity: null
