# Testing configuration for GENESIS IceCube diffusion model
# Fast testing with 10% of data (8% train, 1% val, 1% test)

experiment_name: "icecube_diffusion_testing"
description: "Fast testing configuration with 10% data for quick iteration"

# Model configuration
model:
  seq_len: 5160
  hidden: 16
  depth: 3
  heads: 8
  dropout: 0.1
  fusion: "SUM"
  label_dim: 6
  t_embed_dim: 128
  mlp_ratio: 4.0
  
  # Normalization metadata (for denormalization)
  affine_offsets: [0.0, 0.0, 0.0, 0.0, 0.0]
  affine_scales: [100.0, 10.0, 600.0, 550.0, 550.0]
  label_offsets: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  label_scales: [50000000.0, 1.0, 1.0, 600.0, 550.0, 550.0]
  time_transform: "ln"

# Diffusion configuration
diffusion:
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  objective: "eps"  # "eps" or "x0"
  schedule: "linear"  # "linear" or "cosine"
  
  # Classifier-free guidance
  use_cfg: true
  cfg_scale: 2.0
  cfg_dropout: 0.1

# Data configuration - FAST TESTING MODE
data:
  h5_path: "/home/work/GENESIS/GENESIS-data/22644_0921.h5"
  replace_time_inf_with: 0.0
  channel_first: true
  batch_size: 512
  num_workers: 40
  pin_memory: true
  shuffle: true
  train_ratio: 0.08  # 8% for training
  val_ratio: 0.01    # 1% for validation
  test_ratio: 0.01   # 1% for testing
  
  # Normalization (applied in Dataloader)
  time_transform: "ln"
  affine_offsets: [0.0, 0.0, 0.0, 0.0, 0.0]
  affine_scales: [100.0, 10.0, 600.0, 550.0, 550.0]
  label_offsets: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  label_scales: [50000000.0, 1.0, 1.0, 600.0, 550.0, 550.0]

# Training configuration
training:
  num_epochs: 100
  learning_rate: 0.0001  # Reduced from 2e-4 to 1e-4
  weight_decay: 0.01
  grad_clip_norm: 1.0
  optimizer: "AdamW"
  scheduler: "plateau"  # ReduceLROnPlateau scheduler
  warmup_steps: 1000  # Deprecated, use warmup_ratio
  warmup_ratio: 0.04  # Warmup as 4% of total steps (recommended)
  
  # Scheduler-specific parameters
  cosine_t_max: 2  # T0 (period) = 2 epochs for cosine annealing
  plateau_patience: 2
  plateau_factor: 0.7
  plateau_mode: "min"
  plateau_threshold: 1e-4
  plateau_cooldown: 0
  plateau_verbose: false
  step_size: 30
  step_gamma: 0.1
  linear_start_factor: 1.0
  linear_end_factor: 0.0
  
  # Early stopping
  early_stopping: true
  early_stopping_patience: 5
  early_stopping_min_delta: 1e-4
  early_stopping_mode: "min"
  early_stopping_baseline: null
  early_stopping_restore_best: true
  early_stopping_verbose: true
  
  log_interval: 50
  save_interval: 1000
  eval_interval: 1  # Evaluate every epoch for plateau scheduler
  output_dir: "./outputs"
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"
  resume_from_checkpoint: null
  use_amp: true
  debug_mode: false
  detect_anomaly: false

# System settings
device: "auto"
seed: 42

# Logging
use_wandb: false
wandb_project: "icecube-diffusion"
wandb_entity: null

