# Affine with scale_mult=1.30, centered by empirical median of log10(x).
# z = (log10(x) - center_median) / (scale * scale_mult)
#
# NOTE:
# - method is still "affine".
# - center values below were measured from first 500 LH maps.

normalization:
  Mcdm:
    method: affine
    center: 10.8910
    scale: 0.590
    scale_mult: 1.30
  Mgas:
    method: affine
    center: 10.3545
    scale: 0.627
    scale_mult: 1.30
  T:
    method: affine
    center: 3.9416
    scale: 0.8163
    scale_mult: 1.30
