# Affine with scale_mult=1.40, centered by empirical mean of log10(x).
# z = (log10(x) - center_mean) / (scale * scale_mult)

normalization:
  Mcdm:
    method: affine
    center: 10.9770
    scale: 0.590
    scale_mult: 1.40
  Mgas:
    method: affine
    center: 10.4128
    scale: 0.627
    scale_mult: 1.40
  T:
    method: affine
    center: 4.2362
    scale: 0.8163
    scale_mult: 1.40

